### ISSUE TITLE
No transform from [x] to [base_link]

### ISSUE THREAD

**Issue by broose-goose** [RBinsonB/nexus_4wd_mecanum_simulator#1]
Thank you so much for posting this! 

I recently got a nexus 4wd omni platform and just got the motors and everything talking to ros. When I launched your gazebo program, everything worked as expected, but when I tried opening RVIZ I got a weird error...

The RobotModel displays the base_link, but on every other link it displays "No transform from [x] to [base_link]", and all the wheels are in the middle. Do you know what might be causing this? I tried taking inertial / collision tags out of the xarco file, tried precompiling from xarco to urdf but nothing. Its like RVIZ is completely ignoring the joint tags from the urdf...

![Screenshot from 2020-11-07 22-22-00](https://user-images.githubusercontent.com/49826554/98456922-ba7bc400-2147-11eb-92ae-0333f387ceea.png)

Let me know if you have any ideas of what may be causing this. In the meantime i'll keep banging on it, thanks again!

**Comment by broose-goose** [comment]
Update: if we change the wheels to fixed and have gazebo running, the wheels show up in the correct location! Not sure why that is though; I assume it is because gazebo publishes some message that lets rviz "figure it out". Any thoughts?

**Comment by broose-goose** [comment]
NEVER MIND, GOT IT WORKING!

Had to change the wheel shafts to fixed joints and take out the <axis> tag from those joints as well. Removing the axis tag was the clincher!

**Comment by RBinsonB** [comment]
The gazebo plugin indeed publishes the information needed to get the wheel transforms. If you change the joint to fixed it don't really solves the issue as you just consider the whole robot as one fixed entity. It can be good enough for your application but usually the RViz launch file is called by other launch files with nodes providing their transforms for those links.
